### ISSUE TITLE
Server doesn't start due to anyio issue

### ISSUE THREAD

**Issue by koreyba** [vivekVells/mcp-pandoc#2]
Well, Chat GPT helps me to run this server. 
Chat GPT suggests the anyio library doesn't work or something.

It says I need to execute command:

`mcp-pandoc server`

**This command hangs on execution and returns this log on stopping:**
```
PS C:\Users\John_Doe> mcp-pandoc server
Traceback (most recent call last):
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\streams\memory.py", line 111, in receive
    return self.receive_nowait()
           ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\streams\memory.py", line 106, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcp_pandoc\server.py", line 290, in main
    await server.run(
    ...<10 lines>...
    )
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcp\server\__init__.py", line 423, in run
    async with ServerSession(
               ~~~~~~~~~~~~~^
        read_stream, write_stream, initialization_options
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ) as session:
    ^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcp\shared\session.py", line 122, in __aexit__
    return await self._task_group.__aexit__(exc_type, exc_val, exc_tb)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\_backends\_asyncio.py", line 819, in __aexit__
    raise exc_val
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcp\server\__init__.py", line 426, in run
    async for message in session.incoming_messages:
    ...<69 lines>...
            )
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\abc\_streams.py", line 35, in __anext__
    return await self.receive()
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\streams\memory.py", line 119, in receive
    await receive_event.wait()
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\anyio\_backends\_asyncio.py", line 1809, in wait
    await self._event.wait()
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Scripts\mcp-pandoc.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\site-packages\mcp_pandoc\__init__.py", line 6, in main
    asyncio.run(server.main())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\John_Doe\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt
PS C:\Users\John_Doe>

```

**And there is the log from Claude:**

```
2024-12-10T11:30:45.772Z [info] Attempting to connect to MCP server mcp-pandoc...
2024-12-10T11:30:45.800Z [error] Error in MCP connection to server mcp-pandoc: Error: spawn uvx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn uvx',
  path: 'uvx',
  spawnargs: [Array]
}
2024-12-10T11:30:45.800Z [error] Could not start MCP server mcp-pandoc: Error: spawn uvx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn uvx',
  path: 'uvx',
  spawnargs: [Array]
}
```

**Comment by vivekVells** [comment]
@koreyba  Could you please share the replication steps? 

btw, recently added .docx & .pdf support

**Comment by vivekVells** [comment]
@koreyba Closing this issue. Please reopen or comment with replication steps if you still face the issue. 

Also, added more file conversions support recently. 

https://github.com/vivekVells/mcp-pandoc?tab=readme-ov-file#usage--configuration -> refer this to consume it.
