### ISSUE TITLE
mcp server fails to load

### ISSUE THREAD

**Issue by 1of13** [vivekVells/mcp-pandoc#7]
After adding the following to config, the server fails to load. I have no trouble loading any other mcp servers. Is there another step that I'm missing?

{
  "mcpServers": {
    "mcp-pandoc": {
      "command": "uvx",
      "args": ["mcp-pandoc"]
    }
  }
}

**Comment by adityak74** [comment]
```
{
  "mcpServers": {
    {...other_servers}
    "mcp-pandoc": {
      "command": "uvx",
      "args": ["mcp-pandoc"]
    }
  }
}
```

**Comment by 1of13** [comment]
like i stated earlier, i have no problems with the other mcp servers installed, this is the only one that does not work out of 15--so, it is not the config file.

**Comment by andyvntsys** [comment]
> like i stated earlier, i have no problems with the other mcp servers installed, this is the only one that does not work out of 15--so, it is not the config file.

same here

**Comment by vivekVells** [comment]
Looking into this now. @andyvntsys @1of13

**Comment by vivekVells** [comment]
I couldn't replicate the issue. Let me revert the recent changes for now.

**Comment by vivekVells** [comment]
I've reverted the docx and pdf support changes. After further testing in an isolated environment (to rule out local dependencies like weasyprint), I'll reimplement this feature. 

Thank you @andyvntsys @1of13 for reporting the issue - I've been unable to replicate it on my machine, possibly due to my local weasyprint installation. You should be good now. Let us know if you still face any issues. 

I will keep this thread updated on the progress.

**Comment by vivekVells** [comment]
Finally, got some time today to look into this. And, with some exciting news. 

We have recently merged a feature that supports converting other file formats as well. Right now, mcp-pandoc supports `'html', 'markdown', 'pdf', 'docx', 'rst', 'latex', 'epub', 'txt'`.  -> https://github.com/vivekVells/mcp-pandoc?tab=readme-ov-file#supported-formats

@andyvntsys @1of13 I have verified it locally in my machine & it works as expected. Please let me know if you are good. 

**Verified**

<details>
<summary>Screenshots</summary>
<img width="800" alt="Format conversion interface" src="https://github.com/user-attachments/assets/ce3f5396-252a-4bba-84aa-65b2a06b859e" />
<img width="800" alt="Conversion process" src="https://github.com/user-attachments/assets/8c525ad1-b184-41ca-b068-7dd34b60b85d" />
<img width="800" alt="Output preview" src="https://github.com/user-attachments/assets/a1e0682d-fe44-40b6-9988-bf805627beeb" />
<img width="800" alt="Format selection" src="https://github.com/user-attachments/assets/1d7f5998-6d7f-48fa-adcf-fc37d0521213" />
<img width="800" alt="Conversion complete" src="https://github.com/user-attachments/assets/97992c5d-8efc-40af-a4c3-94c51c392534" />

</details>

**Comment by vivekVells** [comment]
For PDF, ensure to install textlive package. Refer https://github.com/vivekVells/mcp-pandoc?tab=readme-ov-file#%EF%B8%8F-important-notes

**Comment by vivekVells** [comment]
I will keep this issue open for a while & close if no further issues reported.

**Comment by BindingOx** [comment]
What worked for me on windows:

There are two main approaches we can try:

1. **Quick Fix (Temporary)**: 
Before running your script, open Command Prompt and run:
```powershell
setx PYTHONIOENCODING "utf-8"
```
Then try running your script again.

2. **Permanent System-Wide Fix** (recommended):
1. Press Windows + I to open Settings
2. Go to "Time & Language"
3. Click "Language & Region" on the left sidebar
4. Click "Administrative language settings" on the right
5. Click "Change system locale" button
6. Check the box that says "Use Unicode UTF-8 for worldwide language support"
7. Click OK and restart your computer

**Comment by Lindharin** [comment]
I'm trying to load the mcp_pandoc server and it is failing.  Other mcp servers are loading correctly, so I'm doing something wrong here.  I've tried it two ways:
1.  Using the manual published option.  My config file is:
`{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-filesystem",
        "C:\\Users\\jim\\Desktop",
        "C:\\Users\\jim\\Downloads"
      ]
    },
    "fetch": {
      "command": "python",
      "args": [
        "-m",
        "mcp_server_fetch"
      ],
      "env": {
        "DEBUG": "*"
      }
    },
    "obsidian-mcp": {
      "command": "npx",
      "args": [
        "-y",
        "obsidian-mcp",
        "C:\\ObsidianVault\\TsavoCitiesScratchpad"
      ]
    },
    "mcp-pandoc": {
      "command": "uvx",
      "args": ["mcp-pandoc"]
    }
  }
}`
and the error I get in mcp-server-mcp-pandoc.log is:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python313\Scripts\uvx.exe\__main__.py", line 4, in <module>
    from uvx.cli import app
  File "C:\Python313\Lib\site-packages\uvx\cli.py", line 24, in <module>
    from ._python import _get_package_version, _pip, _python_in_venv, _uv
  File "C:\Python313\Lib\site-packages\uvx\_python.py", line 7, in <module>
    from plumbum.cmd import grep  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'grep' from 'plumbum.cmd' (C:\Python313\Lib\site-packages\plumbum\cmd.py)
`
2.  Next I tried using the Smithery option.  I ran:
`npx -y @smithery/cli install mcp-pandoc --client claude`
It says it successfuly installed, and updated the config file to have:
`    "mcp-pandoc": {
      "command": "npx",
      "args": [
        "-y",
        "@smithery/cli",
        "run",
        "mcp-pandoc",
        "--config",
        "\"{}\""
      ]
    }`
Now the mcp-server-mcp-pandoc.log is:
`'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
`
I'm not sure if my error is related to this open issue or not.  Is there anything I should try next?
Thanks!

**Comment by connor4312** [comment]
The tools schema uses `oneOf` at the top level, which neither Claude models nor 4o support. That may be part of the reason folks are having trouble.

**Comment by vivekVells** [comment]
woah! this is super old. and, I lost track of this. apologies.

**Comment by vivekVells** [comment]
🎉 **RESOLVED** in PR #28 - Universal MCP client compatibility & SDK upgrade v0.8.0

**What was fixed:**
- Upgraded MCP SDK from 1.1.0 → 1.13.1 with enhanced stability and loading reliability
- Fixed JSON Schema compatibility issues that could cause server initialization failures
- Improved server startup process and error handling
- Universal compatibility across all MCP clients

**How to get the fix:**
Upgrade to mcp-pandoc v0.8.0:
- `uvx install --upgrade mcp-pandoc`
- Or reinstall: `uvx install mcp-pandoc`

**How to verify the fix:**
1. Update your MCP client configuration with:
   ```json
   {
     "mcpServers": {
       "mcp-pandoc": {
         "command": "uvx",
         "args": ["mcp-pandoc"]
       }
     }
   }
   ```
2. Restart your MCP client (Claude Desktop, etc.)
3. Check that mcp-pandoc appears in your available servers list
4. Verify server shows as connected/loaded without errors
5. Test basic functionality (e.g., try a simple markdown to HTML conversion)

**Expected behavior:**
✅ MCP server loads successfully without errors
✅ Server appears as connected in your MCP client
✅ No loading failures or initialization issues
✅ Document conversion tools are available and working

**⚠️ If the issue persists:**
Please comment below or re-open this issue with:
- Your mcp-pandoc version (`uvx run mcp-pandoc --version`)  
- Your MCP client type and version
- Any error messages from the MCP client logs
- Your exact server configuration

This should now work as expected across all MCP clients! 🚀
